# Generated by Django 5.2.4 on 2025-07-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Formulation", "Formulasi"),
                            ("Filling", "Filling"),
                            ("Inspection", "Inspeksi"),
                            ("Assembly", "Assembly"),
                            ("Blistering", "Blistering"),
                            ("Packaging", "Packaging"),
                            ("Handover", "Handover"),
                            ("Completed", "Selesai"),
                        ],
                        default="Formulation",
                        max_length=50,
                        verbose_name="Status Proses",
                    ),
                ),
                (
                    "qc_sample_received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Sampel Diterima QC"
                    ),
                ),
                (
                    "qc_report_handed_over_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Tanggal Laporan QAR Diserahkan ke QA",
                    ),
                ),
                (
                    "qa_release_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Tanggal Batch Dirilis oleh QA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informasi Batch",
                "verbose_name_plural": "Informasi Batch",
            },
        ),
        migrations.CreateModel(
            name="MergedYield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100)),
                ("product_id", models.CharField(max_length=100)),
                ("formulation_output_pcs", models.FloatField()),
                ("filling_output", models.FloatField()),
                ("inspection_output", models.FloatField()),
                ("assembly_output", models.FloatField()),
                ("blistering_output", models.FloatField()),
                ("packaging_output", models.FloatField()),
                ("handover_output", models.FloatField()),
                ("theoritical_yield_pcs", models.FloatField()),
                ("total_output", models.FloatField()),
                ("yield_percent", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Isi pesan notifikasi.")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link opsional ke halaman detail.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Kode Produk Unik"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Produk")),
                (
                    "theoritical_yield_pcs",
                    models.PositiveIntegerField(verbose_name="Theoretical Yield (pcs)"),
                ),
                (
                    "target_yield_percent",
                    models.FloatField(verbose_name="Target Yield (%)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="yieldapp.batchinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatorYieldData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tanggal_proses",
                    models.DateField(help_text="Tanggal dimulainya proses batch ini"),
                ),
                (
                    "formulation_output_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Output Formulasi (Kg)"
                    ),
                ),
                (
                    "formulation_output_pcs",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Output Formulasi (setara Pcs)",
                    ),
                ),
                ("filling_output", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "inspection_output",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Jumlah Lolos Inspeksi (pcs)",
                    ),
                ),
                (
                    "qc_sample",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Jumlah Sampel QC (pcs)",
                    ),
                ),
                ("assembly_output", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "blistering_output",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "packaging_output",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "handover_output",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Handover to Warehouse (pcs)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_data",
                        to="yieldapp.batchinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Yield Operator",
                "verbose_name_plural": "Data Yield Operator",
                "ordering": ["-tanggal_proses", "batch"],
            },
        ),
        migrations.AddField(
            model_name="batchinfo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="yieldapp.product",
            ),
        ),
    ]
