# Generated by Django 5.2.4 on 2025-07-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yieldapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StagingYieldData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "theoritical_yield_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_yield_percent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "formulation_kg",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "formulation_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "filling_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "inspection_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "qc_sample_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assembly_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "blistering_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "packaging_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "handover_pcs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issue_description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Proses"),
                            ("SUCCESS", "Berhasil Diproses"),
                            ("ERROR", "Gagal Diproses"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
